name: CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    uses: kvncont/gh-workflows/.github/workflows/python-ci.yml@main
    with:
      python-version: 3.14
      zip-name: lambda-${{ github.sha }}.zip
      artifact-name: lambda-${{ github.sha }}
      requirements-file: requirements.txt
      run-tests: true
      run-linting: true

  deploy:
    needs: build
    uses: kvncont/gh-workflows/.github/workflows/aws-lambda-cd.yml@main
    with:
      environment: DEV
      aws-region: us-east-1
      lambda-name: lambda-python
      artifact-name: lambda-${{ github.sha }}
      zip-file: lambda-${{ github.sha }}.zip
      env-file: config/dev.json
      version-description: "Deploy ${{ github.ref_name }}: [${{ github.sha }}]"
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
