name: Release

on:
  release:
    types:
      - published

jobs:
  build:
    uses: kvncont/gh-workflows/.github/workflows/python-ci.yml@feature/python-lambdas-workflows
    with:
      python-version: 3.14
      zip-name: lambda-${{ github.event.release.tag_name }}.zip
      artifact-name: lambda-${{ github.event.release.tag_name }}
      run-tests: false
      run-linting: false

  upload-to-aws-s3:
    needs: build
    uses: kvncont/gh-workflows/.github/workflows/aws-s3-upload.yml@feature/python-lambdas-workflows
    with:
      environment: DEV
      s3-bucket: ${{ vars.AWS_S3_BUCKET }}
      s3-prefix: releases/${{ github.event.release.tag_name }}
      artifact-name: lambda-${{ github.event.release.tag_name }}
      role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  upload-to-gh-release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: lambda-${{ github.event.release.tag_name }}
          path: ./dist

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/*.zip
